// Generated by CoffeeScript 1.3.3

$(function() {
  var s;
  s = new NewTile;
  s.loadConfig();
  s.getPostCount().then(function() {
    return s.getPosts().then(function() {
      return s.draw();
    });
  });
  return s.add_scroll_event();
});
